{% set version = "6.2.1" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: bf4e972a88f8841d8fdc6db1a75e0f8d763e66e3754b03006cbc3854d89f1cb1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - zlib
    - libtiff
    - jpeg
    - freetype
    - tk
  run:
    - python
    - jpeg
    - zlib
    - freetype
    - libtiff
    - olefile
    - tk

test:
  imports:
    - PIL
    - PIL.Image

about:
  home: https://pillow.readthedocs.io
  license: PIL
  license_file: LICENSE
  summary: 'Pillow is the friendly PIL fork by Alex Clark and Contributors'

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
