{% set version = "4.0.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  fn: Pillow-{{ version }}.tar.gz
  url: https://github.com/python-pillow/Pillow/archive/{{ version }}.tar.gz
  sha256: ece687f83a78db7ac608aaa9469fc4d5dbc22757c5bc814cee75f457382d26bc

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - zlib 1.2.*
    - libtiff 4.0.*
    - jpeg 9*
    - freetype 2.6.*
    - tk 8.5.*
  run:
    - python
    - jpeg 9*
    - zlib 1.2.*
    - freetype 2.6.*
    - libtiff 4.0.*

test:
  imports:
    - PIL
    - PIL.Image
  commands:
    - conda inspect linkages -p $PREFIX pillow  # [not win]
    - conda inspect objects -p $PREFIX pillow  # [osx]

about:
  home: http://python-imaging.github.io/
  license: Standard PIL license
  license_file: LICENSE
  summary: 'Pillow is the friendly PIL fork by Alex Clark and Contributors.'

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
