{% set version = "9.0.1" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: 6c8bc8238a7dfdaf7a75f5ec5a663f4173f8c367e5a39f87e720495e1eed75fa
  patches:
    - patches/0001-Build-without-USE_WIN32_FILEIO.patch
    # Backport python-pillow/Pillow#5828 (2 patches), can be dropped for v>=9.0
    - patches/0002-Only-prefer-command-line-tools-SDK-on-macOS-over-the.patch
    - patches/0003-Moved-macOS-SDK-logic-into-a-separate-method.patch

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - zlib
    - lcms2
    - libtiff
    - jpeg
    - openjpeg
    - freetype
    - tk
  run:
    - python
    - jpeg
    - openjpeg
    - zlib
    - freetype
    - libtiff
    - olefile
    - tk

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms
  requires:
    - fsspec
    - requests
    - aiohttp

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  dev_url: https://github.com/python-pillow/Pillow/

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
    - h-vetinari
