{% set version = "8.4.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: b8e2f83c56e141920c39464b852de3719dfbfb6e3c99a2d8da0edf4fb33176ed
  patches:
    - patches/0001-Build-without-USE_WIN32_FILEIO.patch
    # Revert python-pillow/Pillow#5624 as it causes build to pick up wrong MacOS SDK
    - patches/0002-Revert-Prefer-command-line-tools-SDK-on-macOS.patch

build:
  number: 0
  skip: true  # [py==27]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - zlib
    - lcms2
    - libtiff
    - jpeg
    - openjpeg
    - freetype
    - tk
  run:
    - python
    - jpeg
    - openjpeg
    - zlib
    - freetype
    - libtiff
    - olefile
    - tk

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms
  requires:
    - fsspec
    - requests
    - aiohttp

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  dev_url: https://github.com/python-pillow/Pillow/

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
    - h-vetinari
