{% set version = "7.2.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: 97f9e7953a77d5a70f49b9a48da7776dc51e9b738151b22dacf101641594a626

build:
  number: 1
  skip: true  # [py==27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - zlib
    - lcms2
    - libtiff
    - jpeg
    - freetype
    - tk
  run:
    - python
    - jpeg
    - zlib
    - freetype
    - libtiff
    - olefile
    - tk

test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms

about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
