{% set version = "11.3.0" %}

package:
  name: pillow-split
  version: {{ version }}

source:
  url: https://github.com/python-pillow/Pillow/archive/refs/tags/{{ version }}.tar.gz
  sha256: fa4aca745b1e1c733589ebf0ef19491b145dd4225c4aa06958963b4e7f0734cf
  patches:
    - patches/0001-Build-without-USE_WIN32_FILEIO.patch
    # fix provided by upstream maintainer for failing test
    - patches/0002-Added-patch-to-fix-failing-Windows-test.patch
    # windows needs help detecting webpmux & xcb
    - patches/0003-add-XCB_ROOT.patch

build:
  number: 2

requirements:
  host:
    - python

outputs:
  - name: pillow
    script: build_pillow.sh   # [unix]
    script: build_pillow.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
      host:
        - python
        - pip
        - setuptools >=77
        # libraries, c.f. https://github.com/python-pillow/Pillow/blob/9.0.0/setup.py#L30-L38
        - freetype
        # fribidi and libimagequant disabled due to
        # GPL discussion, see #109 and #111
        # - fribidi
        - libjpeg-turbo
        - openjpeg
        - lcms2
        # not available elsewhere
        # currently disabled on windows due to libimagequant depending on llvm-openmp, see
        # https://github.com/pytorch/pytorch/issues/72293
        # - libimagequant  # [x86_64 and not win]
        - libtiff
        - libwebp
        - libxcb
        - tk
        - zlib
      run:
        - python
        - freetype
    test:
      imports:
        - PIL
        - PIL.Image
        - PIL.ImageCms
  - name: pillow-tests
    requirements:
      run:
        - {{ pin_subpackage("pillow", exact=True) }}
    test:
      source_files:
        # from upstream repo
        - Tests/
      files:
        # from recipe; some images cannot be in upstream repo, see Tests/README
        - Tests/images
      requires:
        - pytest
        - pytest-timeout
        # test dependency, see Tests/test_image_access.py
        - setuptools
        - {{ compiler('c') }}
        # for run_test.py
        - fsspec
        - requests
      {% set tests_to_skip = "_not_a_real_test" %}
      # compile smoke test failing to link python3x.lib
      {% set tests_to_skip = tests_to_skip + " or test_embeddable" %}                     # [win]
      # the following needs a viewer which we don't have
      {% set tests_to_skip = tests_to_skip + " or (test_imageshow and test_show)" %}      # [linux]
      # this test is a known failure with libjpeg_turbo, but only marked as such for 2.0 upstream, not 2.x, see
      # https://github.com/python-pillow/Pillow/blob/9.3.0/Tests/test_file_libtiff.py#L885-L891
      {% set tests_to_skip = tests_to_skip + " or test_strip_ycbcr_jpeg_2x2_sampling" %}  # [not osx]
      # skip test that requires an image incorrectly flagged by AV
      {% set tests_to_skip = tests_to_skip + " or (test_tiff_crashes and crash-81154a65438ba5aaeca73fd502fa4850fbde60f8.tif)" %}
      # skip test that requires a missing mimage
      {% set tests_to_skip = tests_to_skip + " or test_tiff_mmap" %}
      # #165: hard fail with no feedback on windows
      {% set tests_to_skip = tests_to_skip + " or test_save_zero" %}  # [win]
      # Freetype 2.14 broke some tests https://github.com/python-pillow/Pillow/issues/9205
      # should be fixed in 2.14.1, and maybe some tests need updating in pillow itself
      # FUTURE: skip for now but readd in pillow 11.4.0 or so
      {% set tests_to_skip = tests_to_skip + " test_default_font_size or test_variation_set_by_axes or test_colr or test_colr_mask or test_default_font" %}
      commands:
        - pytest -vv --tb=long --color=yes -k "not ({{ tests_to_skip }})" --durations=50

about:
  home: https://pillow.readthedocs.io
  license: HPND
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
  dev_url: https://github.com/python-pillow/Pillow/

extra:
  feedstock-name: pillow
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
    - h-vetinari
